### ISSUE TITLE
Site link broken

### ISSUE THREAD

**Issue by chilimangoes** [AKSW/KG2Vec#3]
The website (http://tsoru.aksw.org/kg2vec/) linked from the main page of the repo, and in the paper, seems to be down. I've tried several times over the past few days with no luck.

**Comment by RicardoUsbeck** [comment]
Hi, we are working on it. Thanks for pointing it out. We will let you know.

**Comment by aparcar** [comment]
@chilimangoes please try again, should be fixed

**Comment by chilimangoes** [comment]
Verified that the site is up and I can access. Thanks!
